
let a =  { Customer:
        { id: 25833340,
            address_type_id: 0,
            user_id: 4383180,
            nickname: null,
            address1: '2507 Hannibal Cir',
            address2: '',
            address3: '',
            city: 'Plainfield',
            county: null,
            state_id: 17,
            postal_code: '60586-8072',
            country_id: 1,
            display_id: 0,
            _auditdate: '2018-08-01T04:44:09.000Z',
            first_name: 'Delilah',
            last_name: 'Armenta',
            phone: null,
            qas_validated: null,
            user_verified: null,
            address_category_id: 1,
            order_id: 25746394,
            address_id: 36648959,
            email_id: 37776539,
            phone_id: 23477467,
            subtotal: '108.00',
            taxtotal: '15.14',
            shippingtotal: '0.00',
            address_category: 'normal',
            email: 'darmenta630@gmail.com',
            customer_phone: '815-666-0883',
            state_abbrev: 'IL',
            country_code: 'us' },
    Shipments:
        [ { id: 28695794,
            order_id: 25746394,
            order_shipment_status_id: 4,
            sent_to_erp: 0,
            date_shipped: null,
            first_name: null,
            last_name: null,
            address1: null,
            address2: null,
            address3: null,
            city: null,
            state_id: null,
            postal_code: null,
            country_id: null,
            phone: null,
            email_address: null,
            shipment_method: 8,
            tracking_number: null,
            carrier: null,
            package: 'Y - 13 X 9 X 4',
            weight: '1.73',
            ship_via: 'P07',
            created: '2018-07-31T21:44:10.000Z',
            modified: '2018-08-01T00:45:06.000Z',
            gti_shipment_id: null,
            order_shipment_status: 'Processing',
            order_shipment_method: 'US-ECON' } ],
    RetailRoyalty:
        { id: 21558627,
            royalty_type_id: 1,
            presenter_id: 891177,
            market_id: 1,
            date_earned: '2018-07-31T21:44:12.000Z',
            date_paid: '2018-08-01T01:00:16.000Z',
            date_attempted: '2018-08-01T01:00:13.000Z',
            point_amount: '10.75',
            amount: '10.75',
            withholding: '0.00',
            order_id: 25746394,
            order_percentage: '25.00',
            reference_id: 'YOU03LO9OQDYAV4Z',
            royalty_status_id: 6,
            royalty_status: 'Is Paid' },
    Payments:
        [ { id: 24381855,
            order_id: 25746394,
            order_payment_type_id: 1,
            order_payment_status_id: 3,
            identifier: 3364,
            transactionid: 'qrj6g46e',
            market_id: null,
            date_placed: '2018-07-31T21:44:12.000Z',
            amount: '123.14',
            order_payment_processor_id: 10,
            card_type_id: 2,
            status: 'Success',
            type: 'Credit Card',
            processor: 'TokenEx' } ],
    Items:
        [ { id: 115606192,
            order_customer_id: 25833340,
            order_shipment_id: 28695794,
            item_id: 1749,
            order_item_type_id: 1,
            order_item_hold_code_id: 0,
            parent_id: null,
            promotion_id: 0,
            price: '130.00',
            commission: '130.00',
            quantity: 1,
            discount: '65.00',
            extended_price: '65.00',
            extended_commission: '0.00',
            tax_amount: '11.38',
            handling_fee: '0.00',
            points: 0,
            date_created: '2018-07-31T21:44:09.000Z',
            ns_warehouse_id: 1,
            item_type_id: 4,
            item_sequence: 42018,
            sku: 'US-42018-02',
            name: 'Make the Stars Jealous',
            orderable: 1,
            shippable: 1,
            taxable: 1,
            in_stock: 1,
            enabled: 1,
            redirect_sku: null,
            max_qty: null,
            item_availability_id: 3,
            manufacturer_item_code: null,
            qty_required: null,
            is_prekit: 0,
            weight: '0.00',
            depth: '0.00',
            height: '0.00',
            width: '0.00',
            prop65_flag: null,
            shipment_class: null,
            tax_type_id: 1,
            sync_date: '2018-03-01T13:29:00.000Z',
            is_replaceable: 1,
            customer_visible: 1,
            replace_without_return: 0,
            order_id: 25746394,
            restock_date: null,
            valuation_price: '0.00' },
            { id: 115606193,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 1624,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: null,
                promotion_id: 0,
                price: '24.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '24.00',
                extended_commission: '24.00',
                tax_amount: '2.10',
                handling_fee: '0.00',
                points: 24,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: null,
                sku: 'US-11102-02',
                name: 'Moodstruck Epic Mascara',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.06',
                depth: '5.30',
                height: '0.80',
                width: '0.80',
                prop65_flag: null,
                shipment_class: null,
                tax_type_id: 2,
                sync_date: '2018-01-03T10:16:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '24.00' },
            { id: 115606194,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 623,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: null,
                promotion_id: 0,
                price: '19.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '19.00',
                extended_commission: '19.00',
                tax_amount: '1.66',
                handling_fee: '0.00',
                points: 19,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 11803,
                sku: 'US-11803-01',
                name: 'Moodstruck Opulence Lipstick Affluent',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.06',
                depth: '0.75',
                height: '3.25',
                width: '0.75',
                prop65_flag: null,
                shipment_class: 'D',
                tax_type_id: 3,
                sync_date: '2018-01-03T10:13:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '19.00' },
            { id: 115606195,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 2041,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: null,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 11804,
                sku: 'US-11804-17',
                name: 'Splash Liquid Lipstick - Softhearted',
                orderable: 0,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.08',
                depth: '5.06',
                height: '0.88',
                width: '0.09',
                prop65_flag: null,
                shipment_class: null,
                tax_type_id: 3,
                sync_date: '2018-07-25T11:56:00.000Z',
                is_replaceable: 1,
                customer_visible: 0,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '2.05' },
            { id: 115606196,
                order_customer_id: 25833340,
                order_shipment_id: null,
                item_id: 488,
                order_item_type_id: 2,
                order_item_hold_code_id: 1,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 4,
                item_type_id: 1,
                item_sequence: 12401,
                sku: 'US-12401-01',
                name: 'Beachfront Bronzer - Sunset',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.18',
                depth: '3.44',
                height: '0.69',
                width: '3.38',
                prop65_flag: null,
                shipment_class: 'D',
                tax_type_id: 2,
                sync_date: '2018-01-03T10:13:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: '2018-08-08T00:00:00.000Z',
                valuation_price: '13.28' },
            { id: 115606197,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 639,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 12103,
                sku: 'US-12103-02',
                name: 'Moodstruck Precision Brow Liner - Medium',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.02',
                depth: '5.94',
                height: '0.50',
                width: '0.50',
                prop65_flag: null,
                shipment_class: 'D',
                tax_type_id: 1,
                sync_date: null,
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '7.88' },
            { id: 115606198,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 1183,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 17002,
                sku: 'US-17002-03',
                name: 'Touch à la mode Cream To Powder Luminizer - Benevolent',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.11',
                depth: '3.50',
                height: '1.20',
                width: '1.20',
                prop65_flag: null,
                shipment_class: null,
                tax_type_id: 2,
                sync_date: '2018-01-03T10:13:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '16.18' },
            { id: 115606199,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 1624,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: null,
                sku: 'US-11102-02',
                name: 'Moodstruck Epic Mascara',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.06',
                depth: '5.30',
                height: '0.80',
                width: '0.80',
                prop65_flag: null,
                shipment_class: null,
                tax_type_id: 2,
                sync_date: '2018-01-03T10:16:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '9.96' },
            { id: 115606200,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 471,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 11601,
                sku: 'US-11601-02',
                name: 'Bisque',
                orderable: 1,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.16',
                depth: '5.38',
                height: '1.13',
                width: '2.13',
                prop65_flag: null,
                shipment_class: 'A',
                tax_type_id: 5,
                sync_date: '2018-01-03T09:11:00.000Z',
                is_replaceable: 1,
                customer_visible: 1,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '16.18' },
            { id: 115606201,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 1747,
                order_item_type_id: 1,
                order_item_hold_code_id: 0,
                parent_id: 115606192,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:09.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 61007,
                sku: 'US-61007-04',
                name: 'Spring 2018 Collection Bag',
                orderable: 0,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 1,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: '0.74',
                depth: '7.00',
                height: '0.90',
                width: '10.00',
                prop65_flag: null,
                shipment_class: null,
                tax_type_id: 9,
                sync_date: '2018-02-20T16:43:00.000Z',
                is_replaceable: 0,
                customer_visible: 0,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '1.52' },
            { id: 115606211,
                order_customer_id: 25833340,
                order_shipment_id: 28695794,
                item_id: 372,
                order_item_type_id: 1,
                order_item_hold_code_id: null,
                parent_id: null,
                promotion_id: 0,
                price: '0.00',
                commission: '0.00',
                quantity: 1,
                discount: '0.00',
                extended_price: '0.00',
                extended_commission: '0.00',
                tax_amount: '0.00',
                handling_fee: '0.00',
                points: 0,
                date_created: '2018-07-31T21:44:15.000Z',
                ns_warehouse_id: 1,
                item_type_id: 1,
                item_sequence: 6006,
                sku: 'US-6006-01',
                name: 'Backorder Ticket',
                orderable: 0,
                shippable: 1,
                taxable: 1,
                in_stock: 1,
                enabled: 0,
                redirect_sku: null,
                max_qty: null,
                item_availability_id: 3,
                manufacturer_item_code: null,
                qty_required: null,
                is_prekit: 0,
                weight: null,
                depth: null,
                height: null,
                width: null,
                prop65_flag: 0,
                shipment_class: 'B',
                tax_type_id: 8,
                sync_date: null,
                is_replaceable: 0,
                customer_visible: 0,
                replace_without_return: 0,
                order_id: 25746394,
                restock_date: null,
                valuation_price: '3.67' } ],
    id: 25746394,
    user_id: 4383180,
    presenter_id: 891177,
    promoter_id: 0,
    party_id: 10279334,
    order_type_id: 3,
    order_status_id: 8,
    secondary_order_status_id: '13',
    order_source_id: null,
    market_id: 1,
    order_market_id: 1,
    date_started: '2018-07-31T21:44:09.000Z',
    date_completed: '2018-07-31T21:44:12.000Z',
    subtotal: '108.00',
    shipping_tax: '0.00',
    taxtotal: '15.14',
    vattotal: '0.00',
    shippingtotal: '0.00',
    discount: '0.00',
    commissionable_total: '43.00',
    market_commissionable: '43.00',
    presenter_commissionable: '43.00',
    grand_total: '123.14',
    point_total: '43.00',
    donation: '0.00',
    ip_address: 1227155447,
    _auditdate: '2018-08-01T07:45:06.000Z',
    gti_status_id: null,
    status: 'Processing',
    type: 'Standard',
    presenter_user_id: 4383180,
    secondary_status: 'NetSuite Ready',
    gti_status: null,
    presenter_status_id: 3,
    sponsor_id: 479661,
    first_name: 'Delilah',
    middle_name: null,
    last_name: 'Armenta',
    date_of_birth: '1986-05-30T00:00:00.000Z',
    presenter_sequence_id: 621047,
    presenter_first_name: 'Delilah',
    presenter_last_name: 'Armenta' }


function transformSalesOrderPayload(order) {

    if (!utils.validOrder(order)) {
        return;
    }

    if (Array.isArray(order.Customer)) {
        order.Customer = order.Customer[0];
    }

    let order_items = [];
    let total_item_quantity = 0;
    let subtotal = parseFloat(order.subtotal);
    let declared_per_item_quantity = '0.10';
    let myTaxes = 0.00;
    for (let order_item of order.Items) {
        total_item_quantity += parseInt(order_item.quantity);
        //Need Order Item Recognized Price
        //myTaxes += order_item.OrderItemRecognizedPrice.price_supplement ? parseFloat(order_item.OrderItemRecognizedPrice.price_supplement) : 0.00;
    }

    let excluded_item_types = [
        2, //Variant Master
        3, //Set
        4, //Collection
        6, //Convention Ticket
        8 //Sales Aid Kit
    ]; //Excluded item types.

    for (let order_item of order.Items) {
        //		if(excluded_item_types.includes(order_item.item_type_id))
        //			continue;
        let declared_value = 0;

        if (total_item_quantity >= 1) {
            declared_per_item_quantity = Number((subtotal / total_item_quantity).toFixed(2));
        }

        declared_value = order_item.quantity * declared_per_item_quantity;

        order_items.push({
            "item": order_item.sku,
            "quantity": Math.abs(order_item.quantity),
            "price": "-1",
            "rate": null,
            "amount": order_item.price * Math.abs(order_item.quantity),
            "custcol_orderitemid": order_item.id,
            "custcol_cps_shipment_id": order_item.order_shipment_id,
            "custcol_itemid": order_item.item_id,
            "custcol_parentitemid": order_item.parent_id,
            "custcol_itemdiscount": order_item.discount,
            "custcol_itemtype": order_item.item_type_id,
            "custcol_itemtotal": order_item.extended_price,
            "custcol_declaredvalue": declared_value
        });
    }

    let date_started = utils.convertToDate(order.date_started);
    let date_completed = utils.convertToDate(order.date_completed);

    return {
        'recordtype': 'salesorder',
        'tranid': order.id,
        'externalid': 'SO_' + order.id,
        'custbodyorder_type': order.order_type_id,
        'order_status': order.order_status_id,
        'custbodytax_quote_date': utils.dateFormat(date_started, "%m/%d/%Y %H:%M:%S", true),
        'trandate': utils.dateFormat(date_completed, "%m/%d/%Y", true),
        'custbody_presenter_market': order.market_id,
        'foundation_donation': order.donation && parseFloat(order.donation) > 0.00 ? parseFloat(order.donation) : 0.00,
        'tax': order.taxtotal && parseFloat(order.taxtotal) > 0.00 ? parseFloat(order.taxtotal) : 0.00,
        'custbody_order_market': order.order_market_id,
        'subtotal': subtotal,
        'taxtotal': myTaxes.toFixed(2), //parseFloat(order.taxtotal),
        'shippingcost': parseFloat(order.shippingtotal),
        'discounttotal': parseFloat(order.discount),
        'total': parseFloat(order.grand_total),
        'custbody_presenter': order.presenter_id,
        'shipmethod': order.Shipments[0] ? order.Shipments[0].shipment_method : "0",
        'shipcountry': order.Customer.country_id,
        'shipzip': order.Customer.postal_code,
        'shipaddr1': order.Customer.address1,
        'shipaddr2': order.Customer.address2,
        'shipaddr3': order.Customer.address3,
        'shipcity': order.Customer.city,
        'shipstate': order.Customer.state_id,
        'custbody_event_timestamp': order.timestamp,
        'currency': order.order_market_id,
        'items': order_items,
        'customer': {
            'recordtype': 'customer',
            'autoname': false,
            'firstname': order.Customer.first_name ? order.Customer.first_name.substring(0, 32) : '',
            'lastname': order.Customer.last_name ? order.Customer.last_name.substring(0, 32) : '',
            'currency': order.order_market_id,
            'entityid': order.user_id,
            'email': order.Customer.email,
            'custbody_order_market': order.order_market_id,
            'custentity_event_timestamp': order.timestamp,
            'addressbook': {
                'country': order.Customer.country_id,
                'city': order.Customer.city,
                'state': order.Customer.state_id,
                'zip': order.Customer.postal_code,
                'addr1': order.Customer.address1 ? order.Customer.address1.substring(0, 150) : '',
                'addr2': order.Customer.address2 ? order.Customer.address2.substring(0, 150) : '',
                'addr3': order.Customer.address3 ? order.Customer.address3.substring(0, 150) : '',
                'externalid': order.Customer.address_id
            }
        }
    };
}

transformSalesOrderPayload(a);